# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:  
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpassword
     
    volumes:
      - /home/sri/Desktop/5th_sem/Software engineering/Project/rms/database dump/rms.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "9906:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./rms/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    
